kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-coffeescript
  - jekyll-paginate
baseurl: "/jekyll32" # the subpath of your site, e.g. /blog
description: "Miscellaneous nuggets of knowledge and interest."
title: "Bits of tedium"
